volumes:
  database_data:
    driver: local
  database_test_data:
    driver: local
  cache_data:
    driver: local

services:

  nginx:
    image: nginx:1.23-alpine
    ports:
      - 8088:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    restart: unless-stopped
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/ping"]
      interval: 60s
      timeout: 3s
      retries: 3

  php:
    restart: unless-stopped
    expose:
      - 9000
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - cache_data:/var/www/html/var/cache

  database:
    image: postgres:15.1-alpine3.17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: developer_quotes_sender
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      #- ./docker/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - database_data:/var/lib/postgresql/data
